/* ==========================================================================
   STATE DRAW SYSTEM DATA
   system: "preference" | "bonus" | "lottery" | "mixed" | "otc"
   confidence: "verified"  -> corroborated against the issuing agency or
                              multiple current hunting-industry sources this
                              session
               "general"   -> consistent with published hunting-industry
                              guides but not independently re-verified here;
                              treat point/species details as a starting
                              point and confirm against the agency link
                              before applying.
   points_reset: what zeroes an applicant's points, in plain language
   ========================================================================== */

const STATE_DATA = [
  { code:"AK", name:"Alaska", system:"lottery", confidence:"verified",
    species:["moose","caribou","sheep","goat","deer"],
    notes:"Pure random drawing. No point system exists to build — every application has equal odds every year.",
    agency:"Alaska Dept. of Fish & Game" },
  { code:"AL", name:"Alabama", system:"otc", confidence:"general",
    species:["deer","turkey"],
    notes:"Deer and turkey are largely over-the-counter/unlimited on WMAs with quota permits; a small number of special quota hunts use a lottery.",
    agency:"Alabama Wildlife & Freshwater Fisheries" },
  { code:"AR", name:"Arkansas", system:"lottery", confidence:"general",
    species:["deer","elk","bear"],
    notes:"Special quota hunts (elk, bear, premium deer WMAs) are drawn by lottery; no long-term point bank.",
    agency:"Arkansas Game & Fish Commission" },
  { code:"AZ", name:"Arizona", system:"bonus", confidence:"verified",
    species:["elk","deer","pronghorn","sheep","bear","turkey","javelina","buffalo"],
    notes:"Each bonus point = one extra random-number entry in the draw, in addition to the application's own entry. Points never guarantee a tag.",
    points_reset:"Points return to zero once the species is drawn.",
    agency:"Arizona Game & Fish Department" },
  { code:"CA", name:"California", system:"preference", confidence:"verified",
    species:["deer","elk","pronghorn","sheep"],
    notes:"Modified preference-point system; higher point holders are drawn first for most premium hunts.",
    agency:"California Dept. of Fish & Wildlife" },
  { code:"CO", name:"Colorado", system:"preference", confidence:"verified",
    species:["elk","deer","pronghorn","bear","sheep","moose","goat"],
    notes:"1st-choice round is allocated strictly by preference points, highest first. 2nd–4th choice rounds and the Secondary Draw are random and don't use points. Sheep/moose/goat cap preference points at 3, then switch to weighted bonus points.",
    points_reset:"Points zero out when you draw your first-choice license.",
    agency:"Colorado Parks & Wildlife" },
  { code:"CT", name:"Connecticut", system:"lottery", confidence:"general",
    species:["deer","turkey"],
    notes:"Limited-quota state land hunts are drawn by lottery; no cumulative point bank.",
    agency:"CT Dept. of Energy & Environmental Protection" },
  { code:"DE", name:"Delaware", system:"otc", confidence:"general",
    species:["deer"],
    notes:"Deer licenses are largely over-the-counter; limited special hunts use lottery.",
    agency:"Delaware Div. of Fish & Wildlife" },
  { code:"FL", name:"Florida", system:"lottery", confidence:"general",
    species:["deer","turkey","bear"],
    notes:"Quota hunts on wildlife management areas are drawn by lottery with no long-term point accumulation.",
    agency:"Florida Fish & Wildlife Conservation Commission" },
  { code:"GA", name:"Georgia", system:"lottery", confidence:"general",
    species:["deer","turkey"],
    notes:"Quota WMA hunts are drawn by lottery; general season licenses are OTC.",
    agency:"Georgia Dept. of Natural Resources" },
  { code:"HI", name:"Hawaii", system:"lottery", confidence:"general",
    species:["deer","goat","sheep","pig"],
    notes:"Managed public hunting areas use lottery draws.",
    agency:"Hawaii Dept. of Land & Natural Resources" },
  { code:"IA", name:"Iowa", system:"lottery", confidence:"verified",
    species:["deer"],
    notes:"Nonresident deer is a well-known pure lottery — equal odds regardless of application history.",
    agency:"Iowa Dept. of Natural Resources" },
  { code:"ID", name:"Idaho", system:"lottery", confidence:"verified",
    species:["elk","deer","pronghorn","sheep","goat","moose"],
    notes:"Primarily a pure lottery for controlled hunts; a small number of species/hunts use a limited bonus-weighting. No long-term guarantee system like preference points.",
    agency:"Idaho Fish & Game" },
  { code:"IL", name:"Illinois", system:"lottery", confidence:"general",
    species:["deer","turkey"],
    notes:"Permits for many units are lottery-drawn on a first-come/random basis without a cumulative point bank.",
    agency:"Illinois Dept. of Natural Resources" },
  { code:"IN", name:"Indiana", system:"otc", confidence:"general",
    species:["deer","turkey"],
    notes:"Mostly over-the-counter; a few reserved-hunt lotteries exist.",
    agency:"Indiana Dept. of Natural Resources" },
  { code:"KS", name:"Kansas", system:"lottery", confidence:"verified",
    species:["deer","elk"],
    notes:"Nonresident deer and the limited elk hunts run on random draw without point accumulation.",
    agency:"Kansas Dept. of Wildlife & Parks" },
  { code:"KY", name:"Kentucky", system:"lottery", confidence:"general",
    species:["elk","deer"],
    notes:"Elk permits are a well-known lottery with extremely long odds; no preference/bonus point bank.",
    agency:"Kentucky Dept. of Fish & Wildlife Resources" },
  { code:"LA", name:"Louisiana", system:"lottery", confidence:"general",
    species:["deer","turkey"],
    notes:"WMA lottery hunts exist alongside OTC general season tags.",
    agency:"Louisiana Dept. of Wildlife & Fisheries" },
  { code:"MA", name:"Massachusetts", system:"lottery", confidence:"general",
    species:["deer"],
    notes:"Antlerless deer permits are allocated by a zone-based lottery.",
    agency:"MassWildlife" },
  { code:"MD", name:"Maryland", system:"otc", confidence:"general",
    species:["deer"],
    notes:"Deer licensing is largely over-the-counter.",
    agency:"Maryland Dept. of Natural Resources" },
  { code:"ME", name:"Maine", system:"lottery", confidence:"general",
    species:["moose","deer"],
    notes:"The moose permit lottery is well known; more applications (purchased chances) improve odds but it isn't a preference-point queue.",
    agency:"Maine Dept. of Inland Fisheries & Wildlife" },
  { code:"MI", name:"Michigan", system:"mixed", confidence:"verified",
    species:["deer","elk","bear"],
    notes:"Deer tags are over-the-counter, while elk and bear permits are allocated through a bonus-point lottery draw.",
    agency:"Michigan Dept. of Natural Resources" },
  { code:"MN", name:"Minnesota", system:"lottery", confidence:"general",
    species:["deer","elk","moose"],
    notes:"Elk and moose (where open) and antlerless deer permits in some zones are lottery-drawn.",
    agency:"Minnesota Dept. of Natural Resources" },
  { code:"MO", name:"Missouri", system:"otc", confidence:"general",
    species:["deer","turkey"],
    notes:"Mostly over-the-counter with limited managed-hunt lotteries.",
    agency:"Missouri Dept. of Conservation" },
  { code:"MS", name:"Mississippi", system:"otc", confidence:"general",
    species:["deer","turkey"],
    notes:"Mostly over-the-counter with WMA quota lotteries.",
    agency:"Mississippi Dept. of Wildlife, Fisheries & Parks" },
  { code:"MT", name:"Montana", system:"mixed", confidence:"verified",
    species:["elk","deer","moose","sheep","goat","pronghorn"],
    notes:"Preference points for moose/sheep/goat and the Big Game/Elk/Deer Combination licenses; bonus (squared) points for general deer and elk permits. Applying through a licensed outfitter can add an extra outfitter preference point.",
    agency:"Montana Fish, Wildlife & Parks" },
  { code:"NC", name:"North Carolina", system:"lottery", confidence:"general",
    species:["deer","bear","elk"],
    notes:"Quota hunts (including the small elk season) are lottery-drawn.",
    agency:"NC Wildlife Resources Commission" },
  { code:"ND", name:"North Dakota", system:"lottery", confidence:"general",
    species:["deer","elk","moose","pronghorn","sheep"],
    notes:"Nonresident big game (esp. deer gratis licenses) is capped and drawn; some species use a weighted point system — verify per species.",
    agency:"North Dakota Game & Fish Dept." },
  { code:"NE", name:"Nebraska", system:"mixed", confidence:"verified",
    species:["deer","elk","bighorn sheep"],
    notes:"Uses both lottery drawings (equal odds per application) and preference-point drawings depending on the hunt; bighorn sheep and multispecies combo/super tags are among the preference-point draws.",
    agency:"Nebraska Game & Parks Commission" },
  { code:"NH", name:"New Hampshire", system:"lottery", confidence:"general",
    species:["moose","deer"],
    notes:"Moose permit lottery; more chances can be purchased but it is not a preference queue.",
    agency:"NH Fish & Game Dept." },
  { code:"NJ", name:"New Jersey", system:"otc", confidence:"general",
    species:["deer","bear"],
    notes:"Mostly permit-based over-the-counter, with a managed bear hunt lottery in some years.",
    agency:"NJ Div. of Fish & Wildlife" },
  { code:"NM", name:"New Mexico", system:"lottery", confidence:"verified",
    species:["elk","deer","pronghorn","sheep","oryx","bear"],
    notes:"Pure lottery draw — equal odds for every valid application, no point bank.",
    agency:"New Mexico Dept. of Game & Fish" },
  { code:"NV", name:"Nevada", system:"bonus", confidence:"verified",
    species:["elk","deer","pronghorn","sheep","goat"],
    notes:"Distinctive 'squared' bonus points: your accumulated bonus points are squared, then one chance for the current year is added — a much steeper odds curve than a standard bonus system.",
    agency:"Nevada Dept. of Wildlife" },
  { code:"NY", name:"New York", system:"lottery", confidence:"general",
    species:["deer","bear","turkey"],
    notes:"Nuisance/special hunt permits and some WMU antlerless tags are lottery-based.",
    agency:"NY Dept. of Environmental Conservation" },
  { code:"OH", name:"Ohio", system:"otc", confidence:"general",
    species:["deer","turkey"],
    notes:"Mostly over-the-counter with a handful of controlled-hunt lotteries on public land.",
    agency:"Ohio Dept. of Natural Resources" },
  { code:"OK", name:"Oklahoma", system:"preference", confidence:"verified",
    species:["deer","elk","antelope"],
    notes:"Applicants not drawn receive a preference point for that category; group applications average the group's points. Points lapse after 5 consecutive years of not applying. Elk hunts are drawn first, then antelope, then deer, and drawing one forfeits eligibility for the others that year.",
    agency:"Oklahoma Dept. of Wildlife Conservation" },
  { code:"OR", name:"Oregon", system:"bonus", confidence:"general",
    species:["elk","deer","pronghorn","sheep","goat"],
    notes:"Points-based system that weights the random draw in the applicant's favor without guaranteeing a tag.",
    agency:"Oregon Dept. of Fish & Wildlife" },
  { code:"PA", name:"Pennsylvania", system:"preference", confidence:"general",
    species:["elk"],
    notes:"Elk license draw uses a preference-point-style structure; deer tags are otherwise OTC/allocation-based, not a point draw.",
    agency:"Pennsylvania Game Commission" },
  { code:"RI", name:"Rhode Island", system:"lottery", confidence:"general",
    species:["deer"],
    notes:"Limited management-area hunts are lottery-based.",
    agency:"RI Dept. of Environmental Management" },
  { code:"SC", name:"South Carolina", system:"lottery", confidence:"general",
    species:["deer","turkey"],
    notes:"WMA quota hunts are lottery-drawn; general season is largely OTC.",
    agency:"SC Dept. of Natural Resources" },
  { code:"SD", name:"South Dakota", system:"lottery", confidence:"general",
    species:["deer","elk","antelope","bighorn sheep"],
    notes:"Nonresident big game licenses are capped and drawn; some premium hunts (bighorn sheep) trend toward point-weighted draws — verify per species.",
    agency:"South Dakota Game, Fish & Parks" },
  { code:"TN", name:"Tennessee", system:"lottery", confidence:"general",
    species:["elk","deer","bear"],
    notes:"The elk quota hunt is a well-known lottery; general deer/bear seasons are mostly OTC.",
    agency:"Tennessee Wildlife Resources Agency" },
  { code:"TX", name:"Texas", system:"otc", confidence:"general",
    species:["deer","turkey"],
    notes:"Overwhelmingly private-land and OTC-license driven; the state's Public Hunting drawn-hunt program uses per-hunt random drawings, not a cumulative point bank.",
    agency:"Texas Parks & Wildlife Dept." },
  { code:"UT", name:"Utah", system:"bonus", confidence:"general",
    species:["elk","deer","pronghorn","sheep","goat","bison"],
    notes:"Bonus-point system weighting the random draw; points do not guarantee a tag.",
    agency:"Utah Div. of Wildlife Resources" },
  { code:"VA", name:"Virginia", system:"otc", confidence:"general",
    species:["deer","turkey","bear"],
    notes:"Mostly over-the-counter with limited quota hunts on some WMAs.",
    agency:"Virginia Dept. of Wildlife Resources" },
  { code:"VT", name:"Vermont", system:"lottery", confidence:"general",
    species:["moose","deer"],
    notes:"Moose permit lottery; deer largely OTC.",
    agency:"Vermont Fish & Wildlife Dept." },
  { code:"WA", name:"Washington", system:"bonus", confidence:"general",
    species:["elk","deer","sheep","goat","moose"],
    notes:"Special permit point system weights the random draw for premium hunts.",
    agency:"Washington Dept. of Fish & Wildlife" },
  { code:"WI", name:"Wisconsin", system:"lottery", confidence:"general",
    species:["deer","elk","bear"],
    notes:"Elk and bear permits are lottery-drawn with preference-style bonus in some categories — verify per species; deer is largely OTC.",
    agency:"Wisconsin Dept. of Natural Resources" },
  { code:"WV", name:"West Virginia", system:"lottery", confidence:"general",
    species:["deer","elk","bear"],
    notes:"The newer elk season is a lottery draw; deer/bear are mostly OTC with some quota hunts.",
    agency:"WV Div. of Natural Resources" },
  { code:"WY", name:"Wyoming", system:"preference", confidence:"verified",
    species:["elk","deer","pronghorn","sheep","moose","goat"],
    notes:"Roughly 75% of licenses go to the preference-point pool (highest points first) and 25% to a random draw open to everyone, so even 0-point applicants retain a real chance.",
    agency:"Wyoming Game & Fish Dept." }
];

// Species commonly covered by a points/draw system, used to drive the UI dropdown
const SPECIES_LIST = ["elk","deer","pronghorn","sheep","moose","goat","bear","turkey","bison","javelina"];

if (typeof module !== "undefined") module.exports = { STATE_DATA, SPECIES_LIST };
